Retrofit 설정 및 로그인 API 구현
Keunsori-Developer/towerdle-client pull request #8
Opened 2024-08-14 01:18 UTC by Kim-DG

- [v] Retrofit 설정 완료
- [v] 로그인 API 구현 및 테스트 완료
- [v] authenticate 구현
- [ ] authenticate 테스트

2024-08-16 14:25 UTC, seunggom requested changes

2024-08-16 14:25 UTC, seunggom commented on data/src/main/java/com/keunsori/data/datasource/LocalDataSource.kt
DataStore에 값 읽고 쓸 때에 예외처리 하면 좋을 것 같습니다.

그리고 DataStore 쓰는 것은 좋은데, 사용하는 방식이 잘못된 것 같아요.
DataStore로부터 값을 읽으면 `Flow` 를 반환하는데, 지금 코드를 보면 전혀 Flow, coroutine을 활용하지 않고 refreshToken 값을 refreshToken.first() 를 사용하여 값을 얻어오려고 하고 있는 것이 문제인 것 같습니다.
그래서 RefreshToken이 필요한 지점에서 저 Flow<String>을 구독하여 값을 받아오도록 하든지, 아니면 LocalDataSource 초기화 시점에 최초 한 번만 dataStore로부터 refreshToken 값을 읽어와서 캐싱을 해두든지 하면 좋을 것 같습니다.

2024-08-16 14:25 UTC, seunggom commented on data/src/main/java/com/keunsori/data/datasource/UserRemoteDataSource.kt
> +    private val oauthApiService: OauthRetrofitService
`RetrofitService`와 `OauthRetrofitService`는 무슨 차이 인가요?

그리고 `UserRemoteDataSource` 가 `OauthRetrofitService` 객체를 가지고 있을 필요는 없고, 그 안에 구현되어 있는 OauthApiService 객체를 가지고 있으면 될 것 같습니다.

마침 Hilt 사용하고 있으니, https://jtm0609.tistory.com/22 요고 참고해서 모듈로 빼서 주입되도록 하면 좋을 것 같아요.

2024-08-16 14:25 UTC, seunggom commented on data/src/main/java/com/keunsori/data/api/OauthApiService.kt
> +interface OauthApiService {
```suggestion
interface AuthApiService {
```

Oauth는 사용자 인증과 관련된 프로토콜 이름이라, 요기에는 안맞는 이름인 것 같습니다.

2024-08-16 14:25 UTC, seunggom commented on data/src/main/java/com/keunsori/data/retrofit/RetrofitService.kt
> +            runBlocking {
runBlocking 을 사용하면 UI Thread 가 Blocking 될텐데, 토큰 갱신하는 로직이 오래걸리게 되면 ANR 이 발생할 수 있어 안전한 방식이 아닌 것 같습니다.

2024-08-16 14:25 UTC, seunggom commented on data/src/main/java/com/keunsori/data/retrofit/RetrofitExtension.kt
> +                it.resumeWith(Result.success(res!!)) // respnose가 success일 때 body가 null이면 exception 발생하게 유도
res 가 null 이면 Result.failure 를 반환하면 되는 거 아닌가요? 요 코드의 의도가 궁금합니다.

2024-08-16 15:17 UTC, Kim-DG commented on data/src/main/java/com/keunsori/data/datasource/UserRemoteDataSource.kt
> +    private val oauthApiService: OauthRetrofitService
인증을 위한 Interceptor가 들어간 RetrofitService와 구분하려 따로 구현하였는데 RetrofitService에 두개의 service를 구현하는게 나을까요?

2024-08-16 15:23 UTC, seunggom commented on data/src/main/java/com/keunsori/data/datasource/UserRemoteDataSource.kt
> +    private val oauthApiService: OauthRetrofitService
아하 RetrofitService 안에서 두 개의 Service를 관리하는 것도 좋아보입니다요

2024-08-16 15:58 UTC, seunggom commented on data/src/main/java/com/keunsori/data/datasource/UserRemoteDataSource.kt
> +    private val oauthApiService: OauthRetrofitService
어차피 NetworkModule 하나 만들면 되기 땜에 RetrofitService 클래스도 굳이 필요 없을 것 같습니다

2024-08-19 09:13 UTC, Kim-DG commented on data/src/main/java/com/keunsori/data/retrofit/RetrofitService.kt
> +            runBlocking {
수정했는데 조금 코드가 복잡한거 같아서 확인 한번 부탁드립니다

https://github.com/Keunsori-Developer/towerdle-client/pull/8/files#diff-34f120cb7951fc6e67750baffcd26f47416f48394c79b8d4feb4440b4a95f236:~:text=randommagic.xyz%22-,%40Provides,%7D,-%40AuthInterceptorOkHttpClient

2024-08-19 09:13 UTC, Kim-DG commented on data/src/main/java/com/keunsori/data/datasource/LocalDataSource.kt
refreshToken은 지속적으로 데이터를 받아올 필요가 없을 것 같아 collect를 사용하여 구독하지 않고 필요한 시점에 한번만 가져와도 될 것 같아 first()를 사용했는데 혹시 이러한 경우에도 Flow를 활용하는게 좋을까요? 지금은 후자의 방법으로 수정 하였습니다.

2024-08-19 09:14 UTC, Kim-DG commented on data/src/main/java/com/keunsori/data/retrofit/RetrofitExtension.kt
> +                it.resumeWith(Result.success(res!!)) // respnose가 success일 때 body가 null이면 exception 발생하게 유도
Result.success라도 res가 null이 아니란걸 보장할 수 없어 위의 방식으로 구현하였습니다.
다시 생각해보니 에러를 발생시키는 것 보다 분기 조건을 더 추가하면 좋을 것 같아 수정하였습니다.

https://github.com/Keunsori-Developer/towerdle-client/pull/8/files#diff-9fd3ff093955e0844f0c40e797f7b534715a10bfd0f30a4ebb11004d6f1ecb02:~:text=%3D%20response.body()-,if%20(response.isSuccessful%20%26%26%20res%20!%3D%20null)%20%7B,%7D,-%7D

2024-08-22 00:58 UTC, seunggom commented on data/src/main/java/com/keunsori/data/datasource/LocalDataSource.kt
first()도 가능하긴 한데, 호출 시점에 따라 수집된 데이터가 하나도 없으면 exception이 발생할 수 있을 것 같습니다.

저 같은 경우엔 데이터를 1개만 수집하고자 할 때에는 flow.**take(1)**.collect {} 이런식으로 사용했습니닷

2024-09-17 05:42 UTC, seunggom approved these changes

2024-09-17 05:44 UTC, seunggom commented
dev에 머지해주시면 rebase 해서 작업하겠슴다

2024-09-22 10:18 UTC, merged